{% set name = "wagtail-flags" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtail-flags-{{ version }}.tar.gz
  sha256: fb7c2e82fed1190b51a386abdc30e0f4f7e413f3c535dfc0dad65ae4c3ef36f7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - wagtail >=4
    - django-flags >4.2

test:
  imports:
    - wagtailflags
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Feature flags for Wagtail sites
  home: https://github.com/cfpb/wagtail-flags
  license: CC0-1.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
